### ISSUE TITLE
Variable Product Bug: Attributes->Options

### ISSUE THREAD

**Issue by DifTechDesigns** [woocommerce/woocommerce-rest-api-docs#158]
In creating product variation, if an option for an attribute is an integer, it fails. Generally, options are words anyway, but I was generating test products and looped through variations and just named the options according the iteration of the loop.

`$data = [
    'regular_price' => '9.00',
    'image' => [
        'id' => 423
    ],
    'attributes' => [
        [
            'id' => 9,
            'option' => 1 //This fails because it's an integer
        ]
    ]
];

$data = [
    'regular_price' => '9.00',
    'image' => [
        'id' => 423
    ],
    'attributes' => [
        [
            'id' => 9,
            'option' => '1' //This works because it's a string
            //'option' => strval(1) also works.
        ]
    ]
];

**Comment by jobthomas** [comment]
Hey @DifTechDesigns that would be as expected indeed. The `option` attribute for a variation is listed as a `string` here: https://woocommerce.github.io/woocommerce-rest-api-docs/#product-variation-properties

Are you suggesting this should be changed? Or something else?

**Comment by DifTechDesigns** [comment]
> Are you suggesting this should be changed? Or something else?

It doesn't make sense that it would require a string as opposed to accepting an integer or a decimal as is or doing the type conversion automatically in code.

At the very least, I think a type warning would be helpful when it errors out. It just never occurred to me that it wouldn't accept an integer, so I never looked at the field specs.

**Comment by claudiosanches** [comment]
Hi there. GitHub is primarily for reporting issues with this documentation, not the REST API implementation, and is not a support forum. We don’t support custom development here. You could ask on the community support forum here: https://wordpress.org/support/plugin/woocommerce

**Comment by jobthomas** [comment]
@claudiosanches we did point @DifTechDesigns here after they tweeted to `@woocommerce` and we weren't entirely sure what the problem was. It seems to me like this is not really a support request but rather a discussion on whether or not the REST API should accept integers where it now only accepts strings. 

@DifTechDesigns, we should've sent you here: https://github.com/woocommerce/woocommerce-rest-api and not to this repo for the docs only. 

@claudiosanches, I presume you mean that this is not something you'd be willing to change/discuss. If you would like to discuss this, let's move it over to the right repo.

**Comment by claudiosanches** [comment]
@jobthomas The correct place to discuss about REST API is in https://github.com/woocommerce/woocommerce-rest-api, here is only with the documentation.

Still this is not something that we should change, since on the back-end everything are strings, so we should not change this behavior only in the REST API, since may cause problems in the back-end in another places on WooCommerce.
