### ISSUE TITLE
List all products string filters better description

### ISSUE THREAD

**Issue by jnhghy** [woocommerce/woocommerce-rest-api-docs#179]
**WC 4.5.2**

Some of the filters for the List all products endpoint accept a comma-separated string of values. The documentation doesn't specify this anywhere and it is unclear if this is the desired thing and it will remain like this in the future or if it is an edge case usage of the field that can break in the future.

For example the SKU, the documentation is like this:

sku | string | Limit result set to products with a specific SKU.

But a request done with multiple SKUs comma-separated will bring multiple products so basically at this point the field can accept a list of SKUs and the response to this will be a multi-product list.

**Comment by jnhghy** [comment]
This ticket seems to be related to this: https://github.com/woocommerce/woocommerce-rest-api-docs/issues/177

**Comment by claudiosanches** [comment]
Hello @jnhghy,

We list those in "Available parameters": https://woocommerce.github.io/woocommerce-rest-api-docs/#list-all-products

SKU's are a especial case only supported in core, but undocumented because it can cause some issues if you are using commands inside your SKUs, also we should change it soon a future version, so this is why we don't document it, it's because we don't recommend.

**Comment by jnhghy** [comment]
@claudiosanches Thanks for clearing things up, since its not recommended I won't touch it...
